# Generated by Django 5.0.4 on 2024-04-16 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Posts_Table',
        ),
    ]
