# Generated by Django 5.0.4 on 2024-04-19 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_posts_table_options_posts_table_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts_table',
            options={'ordering': ['-publish'], 'verbose_name': 'post'},
        ),
    ]
