# Generated by Django 5.0.4 on 2024-04-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_posts_table_post_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_table',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='publish'),
        ),
    ]
