# Generated by Django 5.0.4 on 2024-05-15 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_post_comment_post_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Comment_Table',
        ),
        migrations.RenameIndex(
            model_name='comment_table',
            new_name='blog_commen_created_7d6e63_idx',
            old_name='blog_commen_created_0e6ed4_idx',
        ),
    ]
