# Generated by Django 5.0.4 on 2024-06-10 19:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_comment_comment_table_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post_table',
            name='blog_post_t_publish_bd5c03_idx',
        ),
        migrations.AddIndex(
            model_name='post_table',
            index=models.Index(fields=['publish'], name='blog_post_t_publish_01ead1_idx'),
        ),
    ]
