# Generated by Django 5.0.4 on 2024-08-09 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_post_table_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post_table',
            options={'ordering': ['-publish'], 'verbose_name': 'post'},
        ),
    ]
